require 'bundler/setup'
require 'helix_runtime/build_task'
require_relative '../shared.rb'

# For Windows
$stdout.sync = true

HelixRuntime::BuildTask.new do |t|
  t.build_root = File.expand_path("../..", __dir__)
  t.helix_lib_dir = File.expand_path("../../ruby/windows_build", __dir__)
  t.pre_build = HelixRuntime::Tests.pre_build
end

task :default => :build
