source 'https://rubygems.org'

gem 'libcruby_sys', git: 'https://github.com/tildeio/libcruby-sys', branch: 'helix'
gem 'helix_runtime', path: '../../ruby'
gem 'rake', '~> 10.0'
gem 'rspec', '~> 3.4'
gem 'colorize'
