require 'rake/clean'
require 'rspec/core/rake_task'
require 'bundler/setup'
require_relative File.expand_path('../../shared/platform', __FILE__)

directory 'lib/console'

namespace :cargo do
  task :build do
    sh "cargo rustc --release -- -C link-args='-Wl,-undefined,dynamic_lookup'"
  end

  task :clean do
    sh "cargo clean"
  end
end

task :clobber => "cargo:clean"

file "lib/console/native.#{Platform.dlext}" => ["lib/console", "cargo:build"] do
  cp "../../target/release/libconsole.#{Platform.libext}", "lib/console/native.#{Platform.dlext}"
end
CLOBBER.include("lib/console/native.#{Platform.dlext}")

task :irb => "lib/console/native.#{Platform.dlext}" do
  exec "irb -Ilib -rconsole"
end

RSpec::Core::RakeTask.new(:rspec) do |t|
  t.verbose = false
end

task :rspec => "lib/console/native.#{Platform.dlext}"
task :default => :rspec
