require 'bundler/setup'
require 'helix_runtime/build_task'
require 'rspec/core/rake_task'

HelixRuntime::BuildTask.new("console") do |t|
  t.build_path = File.expand_path("../../../target/release", __FILE__)
  t.helix_lib_dir = File.expand_path("../../../ruby/windows_build", __FILE__)
end

RSpec::Core::RakeTask.new(:spec) do |t|
  t.verbose = false
end

task :spec => :build
task :default => :spec
