require 'bundler/setup'
require 'rspec/core/rake_task'

$example_name = 'console'
import File.expand_path("../../shared/example.rake", __FILE__)

RSpec::Core::RakeTask.new(:spec) do |t|
  t.verbose = false
end

task :spec => :build_native
task :test => :spec
task :default => :spec
