require 'bundler/setup'
require 'helix_runtime/build_task'
require 'rake/testtask'

# For Windows
$stdout.sync = true

HelixRuntime::BuildTask.new("duration") do |t|
  t.build_root = File.expand_path("../..", __dir__)
  t.helix_lib_dir = File.expand_path("../../ruby/windows_build", __dir__)
end

task :build_helix_runtime do
  Dir.chdir("../../ruby") do
    puts "\n\nBuilding helix runtime\n\n"
    Bundler.with_clean_env do
      sh "bundle exec rake compile:native"
    end
    puts "\nRuntime built\n\n"
  end
end
task :build => :build_helix_runtime

Rake::TestTask.new(:test) do |t|
  t.libs << "test"
  t.libs << "lib"
  t.test_files = FileList["test/**/*_test.rb"]
end

task :test => :build

task "test:all" do
  ['RUST', 'RAILS'].each do |impl|
    sh({ 'IMPLEMENTATION' => impl }, 'rake test')
  end
end

task :default => "test:all"
