require 'rake/clean'
require 'rake/testtask'
require 'bundler/setup'
require 'bundler/gem_tasks'

directory 'lib/duration'

namespace :cargo do
  task :build do
    sh "cargo rustc --release -- -C link-args='-Wl,-undefined,dynamic_lookup'"
  end

  task :clean do
    sh "cargo clean"
  end
end

task :clobber => "cargo:clean"

file "lib/duration/native.bundle" => ["lib/duration", "cargo:build"] do
  cp "../../target/release/libduration.dylib", "lib/duration/native.bundle"
end
CLOBBER.include("lib/duration/native.bundle")

task :irb => "lib/duration/native.bundle" do
  exec "irb -Ilib -rduration"
end

task :benchmark => "lib/duration/native.bundle" do
  exec "ruby -Ilib benchmark.rb"
end

Rake::TestTask.new(:test) do |t|
  t.libs << "test"
  t.libs << "lib"
  t.test_files = FileList["test/**/*_test.rb"]
end

task :test => "lib/duration/native.bundle"
task :default => :test
