require 'bundler/setup'
require 'helix_runtime/build_task'
require 'rake/testtask'

ENV['HELIX_ROOT'] = File.expand_path("../../..", __FILE__)

HelixRuntime::BuildTask.new("turbo_blank") do |t|
  t.build_path = File.expand_path("../../../target/release", __FILE__)
end

task :benchmark => "turbo_blank:build" do
  exec "ruby -Ilib benchmark.rb"
end

Rake::TestTask.new(:test) do |t|
  t.libs << "test"
  t.libs << "lib"
  t.test_files = FileList["test/**/*_test.rb"]
end

task :test => "turbo_blank:build"
task :default => :test
