require 'bundler/setup'
require 'rake/testtask'

$example_name = 'membership'
import File.expand_path("../../shared/example.rake", __FILE__)

task :benchmark => :build_native do
  exec "ruby -Ilib benchmark.rb"
end

Rake::TestTask.new(:test) do |t|
  t.libs << "test"
  t.libs << "lib"
  t.test_files = FileList["test/**/*_test.rb"]
end

task :test => :build_native
task :default => :test
