require 'bundler/setup'
require 'helix_runtime/build_task'
require 'rspec/core/rake_task'

ENV['HELIX_ROOT'] = File.expand_path("../../..", __FILE__)

HelixRuntime::BuildTask.new("membership") do |t|
  t.build_path = File.expand_path("../../../target/release", __FILE__)
end

task :benchmark => "membership:build" do
  exec "ruby -Ilib benchmark.rb"
end

RSpec::Core::RakeTask.new(:spec) do |t|
  t.verbose = false
end

task :spec => "membership:build"
task :test => :spec
task :default => :spec
